model_name: mobilenet_v2
epochs: 5
dataset: TaxonomicOrchid
batch_size: 32
# learning_rate: 0.001
# train_split: 0.8
# test_split: 0.1
img_size: 224
data_augmentation: 1

callbacks:
  - ModelCheckpoint
  - EarlyStopping

ModelCheckpoint_monitor: val_loss
ModelCheckpoint_save_best_only: true
EarlyStopping_patience: 5
ReduceLROnPlateau_factor: 0.1

